version: '3'
services:
 dnsmasq:
   image: docker-dnsmasq
   container_name: dnsmasq
   volumes:
     - /srv/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
     - /srv/dnsmasq/dnsmasq.d:/etc/dnsmasq.d
   network_mode: "host"
   restart: always
